title: "Loggbok"
author: "Denis"
description: "Passiert und notiert."
permalink: /:title/
lang: "de"
excerpt_separator: "\n\n\n"
date_format: "%d.%m.%Y"

# Layout

show_excerpts: true       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "README.md"}
  - {file: "blogroll.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
